version: '2'

services:
    application:
        container_name: training_application
        restart: always
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: training_workspace
        restart: always
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: training_php-fpm
        restart: always
        image: framgia/laravel-php-fpm
        volumes_from:
            - application
            - data
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: training_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - application
        ports:
            - "8080:80"
        links:
            - php-fpm
    data:
        container_name: training_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql2
            - .docker/data:/data
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/php-fpm:/var/log/php-fpm
            - .docker/logs/mysql:/var/log/mysql2

    mysql:
        container_name: training_mysql
        restart: always
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
        volumes:
            - ./.docker/provision/mysql/init:/docker-entrypoint-initdb.d
        volumes_from:
            - data
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
